name: Update GitHub Lang Stats SVG

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Щонеділі о 00:00 UTC

permissions:
  contents: write # Дає токену права на пуш

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v4

      - name: Створити рядок часу
        id: generate_time
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          safe_time=$(echo "$current_time" | sed 's/ /%20/g') # Замінюємо пробіли на %20
          echo "TIME_STRING=${safe_time}" >> $GITHUB_ENV

      - name: Завантаження SVG з API
        run: |
          title="VADIM4WEB%27s%20Lang%20Stack%20(updated:%20${{ env.TIME_STRING }})"
          curl -sL "https://github-lang-stats-node.onrender.com/?view=ring&title=${title}" -o data/lang-stats.svg
          echo "✅ SVG збережено"

      - name: Коміт та пуш оновленого SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/lang-stats.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Автоматичне оновлення мов програмування" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vadim4web/vadim4web.git main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
