name: Update GitHub Lang Stats SVG

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Щонеділі о 00:00 UTC

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v4

      - name: Завантаження SVG з API
        run: |
name: Update GitHub Lang Stats SVG

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Щонеділі о 00:00 UTC

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v4

      - name: Завантаження SVG з API
        run: |
          curl -sL "https://github-lang-stats-node.onrender.com/?view=ring&title=VADIM4WEB's%20Lang%20Stack%20(updated:%20$(date '+%Y-%m-%d%20%H:%M:%S'))" -o data/lang-stats.svg
          echo "✅ SVG збережено"

      - name: Коміт та пуш оновленого SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/lang-stats.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Автоматичне оновлення мов програмування" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

          echo "✅ SVG збережено"

      - name: Коміт та пуш оновленого SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/lang-stats.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Автоматичне оновлення мов програмування" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
